In [2]:
# ==============================
# Data Handling
# ==============================
import numpy as np
import pandas as pd

# ==============================
# Visualization
# ==============================
import matplotlib.pyplot as plt
import seaborn as sns

# ==============================
# TensorFlow / Keras
# ==============================
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Input,
    Embedding,
    SimpleRNN,
    LSTM,
    GRU,
    Dense,
    Dropout,
    Bidirectional,
    Flatten
)

# ==============================
# Preprocessing
# ==============================
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# ==============================
# Evaluation
# ==============================
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [27]:
df=pd.read_csv("quotes.csv")
df = df.dropna(subset=["quote"])
df.head()

,index,quote,author,tags,likes
0,0,Be yourself; everyone else is already taken.,Oscar Wilde,attributed-no-source;be-yourself;honesty;inspi...,149270
1,1,You've gotta dance like there's nobody watching,William W. Purkey,dance;heaven;hurt;inspirational;life;love;sing,118888
2,2,Be the change that you wish to see in the world.,Mahatma Gandhi,action;change;inspirational;philosophy;wish,106749
3,3,No one can make you feel inferior without your...,"Eleanor Roosevelt,",confidence;inspirational;wisdom,85854
4,4,Live as if you were to die tomorrow. Learn as ...,Mahatma Gandhi,carpe-diem;education;inspirational;learning,73033

In [28]:
quote=df["quote"]
quote

0            Be yourself; everyone else is already taken.
1         You've gotta dance like there's nobody watching
2        Be the change that you wish to see in the world.
3       No one can make you feel inferior without your...
4       Live as if you were to die tomorrow. Learn as ...
                              ...
2996    And this is for Colored girls who have conside...
2997    After all, when you come right down to it, how...
2998    Aku telah mengidap sakit gila nomor enam belas...
2999    The moon is the reflection of your heart and m...
3000    But in the end it's only a passing thing, this...
Name: quote, Length: 2996, dtype: str

In [29]:
import string



quote = (
   quote
    .str.lower()
    .str.translate(str.maketrans("", "", string.punctuation))
    .str.strip()
)

In [30]:
quote.isnull().sum()

np.int64(0)

In [31]:
vocab_size=10000
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quote)
sequences = tokenizer.texts_to_sequences(quote)

In [32]:
sequences

[[13, 60, 217, 168, 5, 518, 719],
 [261, 846, 396, 55, 284, 497, 1133],
 [13, 1, 102, 10, 3, 327, 2, 80, 9, 1, 42],
 [35, 31, 23, 52, 3, 128, 3515, 132, 12, 2393],
 [76, 29, 22, 3, 93, 2, 198, 285, 136, 29, 22, 3, 93, 2, 76, 373],
 [359,
  150,
  921,
  73,
  359,
  45,
  191,
  23,
  25,
  10,
  313,
  150,
  921,
  73,
  313,
  45,
  39,
  23,
  25,
  10],
 [132, 439, 21, 117, 13, 7, 537],
 [15, 314, 1, 39, 15, 79, 15, 720],
 [1837, 5, 222, 1134, 5, 1838, 4, 50, 113, 2, 13, 1537, 1839, 54, 1537, 1538],
 [34,
  16,
  45,
  196,
  478,
  2,
  76,
  12,
  21,
  31,
  5,
  29,
  246,
  97,
  5,
  7,
  922,
  1,
  94,
  5,
  29,
  246,
  104,
  5,
  7,
  922],
 [15, 16, 24, 9, 1, 3516, 20, 118, 6, 58, 16, 315, 44, 1, 328],
 [1135,
  1539,
  16,
  56,
  54,
  169,
  14,
  59,
  33,
  193,
  58,
  10,
  1281,
  721,
  20,
  59,
  33,
  193,
  58,
  10,
  1281,
  23,
  13,
  1840],
 [498,
  5,
  456,
  285,
  5,
  7,
  1020,
  170,
  5,
  7,
  291,
  6,
  98,
  95,
  5,
  201,
  15,
  457,
  8,
  1,
  346],
 [11, 18, 14, 1282, 316, 70, 334, 3517, 478, 10, 458, 149],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4,
  1,
  1021,
  6,
  21,
  5,
  14,
  212,
  50,
  1283],
 [11,
  84,
  141,
  6,
  78,
  1284,
  2,
  1285,
  2394,
  239,
  38,
  499,
  499,
  5,
  56,
  190,
  54,
  519,
  519,
  5,
  1540,
  499,
  3520,
  1,
  42],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4,
  3,
  16,
  1,
  31,
  3521,
  538,
  134,
  2,
  81],
 [8, 5, 43, 137, 1841, 2, 13, 19, 3, 317, 18, 116],
 [41,
  21,
  5,
  19,
  3,
  52,
  8,
  35,
  153,
  19,
  108,
  120,
  2,
  923,
  62,
  158,
  50,
  7,
  1842,
  213,
  20,
  1,
  101,
  318,
  5,
  3,
  77,
  2,
  538,
  64,
  108,
  120,
  2,
  923,
  8,
  62,
  1287,
  27,
  13,
  12,
  347,
  1843,
  257,
  55,
  8,
  669,
  20,
  70,
  200,
  118,
  121,
  118,
  81,
  1,
  229,
  10,
  319,
  26,
  3,
  145,
  104,
  412,
  12,
  169,
  135,
  347,
  49,
  82,
  81,
  6,
  57,
  303,
  200,
  1844,
  52,
  1,
  135,
  347,
  9,
  1,
  42,
  29,
  17,
  2396,
  207,
  1843,
  121,
  4,
  81,
  137,
  4,
  3522,
  11,
  313,
  2,
  126,
  8,
  111,
  6,
  57,
  539,
  1023,
  114,
  24,
  6,
  57,
  16,
  120,
  2,
  413,
  12,
  87,
  20,
  3,
  147,
  112,
  62,
  59,
  22,
  3,
  112,
  62,
  247,
  43,
  122,
  12,
  3523,
  247,
  43,
  122,
  10,
  629,
  28,
  171,
  3,
  292,
  4,
  10,
  566,
  17,
  104,
  70,
  59,
  3,
  440,
  181,
  241,
  274,
  108,
  924,
  440,
  44,
  104,
  138,
  248,
  320,
  37,
  4,
  67,
  67,
  67,
  115,
  9,
  60,
  59,
  22,
  3,
  49,
  96,
  28,
  27,
  3524,
  51,
  138,
  12,
  286,
  397,
  138,
  12,
  1845,
  62,
  4,
  111,
  2397,
  138,
  925,
  59,
  459,
  7,
  172,
  86,
  4,
  284,
  51,
  114,
  2,
  329,
  68],
 [34, 5, 35, 335, 1541, 54, 2398, 78, 2399, 414, 321, 3],
 [104, 3, 23, 779, 5, 219],
 [3,
  23,
  43,
  77,
  7,
  1846,
  6,
  2400,
  1847,
  141,
  32,
  7,
  398,
  176,
  141,
  2,
  1848,
  46],
 [2, 1, 3525, 139, 212, 5, 20, 1, 540, 124, 596],
 [21, 348, 68, 670, 60, 21, 5, 68, 1288, 60],
 [25, 19, 3, 23, 26, 19, 3, 18, 134, 3, 16],
 [280,
  2,
  1,
  3526,
  336,
  280,
  2,
  1,
  3527,
  280,
  2,
  1,
  3528,
  1,
  3529,
  1,
  3530,
  280,
  2,
  1,
  43,
  3531,
  96,
  280,
  630,
  2,
  46,
  182,
  23,
  304,
  336,
  182,
  23,
  13],
 [30,
  31,
  722,
  6,
  165,
  2401,
  156,
  2402,
  20,
  349,
  15,
  133,
  51,
  176,
  44,
  1,
  1289,
  722,
  10,
  15,
  25,
  14,
  80,
  1,
  31,
  95,
  83,
  116,
  1290,
  17,
  58],
 [322, 5, 14, 1024, 337, 5, 14, 3532, 8, 5, 1, 237, 2, 1025, 10, 1291],
 [51,
  41,
  5,
  38,
  21,
  4,
  11,
  69,
  3,
  2,
  61,
  10,
  11,
  84,
  520,
  202,
  4,
  671,
  4,
  161,
  151,
  248,
  2,
  2403,
  73,
  64,
  10,
  143,
  13],
 [3,
  105,
  126,
  161,
  7,
  1136,
  20,
  161,
  14,
  1,
  45,
  31,
  11,
  208,
  926,
  247,
  1849,
  58,
  4,
  1,
  42,
  27,
  76,
  29,
  31],
 [4, 30, 3, 69, 74, 24, 1, 293, 2404, 9, 927, 3, 2, 415, 8],
 [40,
  672,
  183,
  5,
  14,
  10,
  15,
  16,
  1850,
  40,
  672,
  183,
  5,
  10,
  15,
  16,
  426,
  323,
  847,
  8,
  5,
  40,
  191,
  14,
  40,
  359,
  10,
  111,
  1851,
  58,
  15,
  275,
  203,
  28,
  84,
  11,
  2,
  13,
  1852,
  1542,
  1137,
  1543,
  539,
  28,
  16,
  3,
  14,
  2,
  13,
  3,
  16,
  7,
  336,
  6,
  98,
  12,
  1853,
  269,
  142,
  14,
  723,
  1,
  42,
  34,
  5,
  97,
  2405,
  68,
  3533,
  51,
  10,
  94,
  36,
  458,
  128,
  1854,
  209,
  3,
  15,
  16,
  24,
  441,
  2,
  597,
  29,
  350,
  25,
  15,
  93,
  351,
  2,
  52,
  2406,
  1,
  1292,
  6,
  98,
  10,
  5,
  242,
  58,
  50,
  14,
  70,
  9,
  118,
  6,
  58,
  50,
  9,
  217,
  4,
  29,
  15,
  82,
  40,
  75,
  191,
  597,
  15,
  3534,
  112,
  94,
  36,
  1544,
  2,
  25,
  1,
  154,
  29,
  15,
  16,
  3535,
  65,
  40,
  75,
  183,
  40,
  1545,
  3536,
  1855,
  109],
 [197, 35, 442, 120, 177, 2, 498, 59, 11, 63, 7, 230, 123, 96],
 [19,
  108,
  1138,
  2,
  25,
  30,
  3,
  49,
  55,
  7,
  86,
  5,
  102,
  8,
  22,
  3,
  147,
  102,
  8,
  102,
  1,
  71,
  3,
  79,
  68,
  8,
  49,
  1546],
 [50, 1, 1293, 6, 427, 7, 179, 121, 169, 10, 171, 21, 1294],
 [7, 631, 7, 123, 35, 153, 64, 269],
 [1547,
  14,
  294,
  3,
  3537,
  443,
  4,
  1,
  196,
  6,
  3,
  27,
  43,
  13,
  294,
  20,
  22,
  47,
  23,
  52,
  3,
  567,
  44,
  360,
  181,
  1856,
  3,
  2,
  79,
  1857,
  4,
  22,
  47,
  3538,
  2,
  88,
  152,
  4,
  399,
  287,
  320,
  1295,
  130,
  4,
  112,
  130,
  1,
  111,
  3,
  23,
  47,
  1296,
  120,
  2,
  3539,
  1858,
  1547,
  14,
  338,
  68,
  3,
  85,
  162,
  20,
  47,
  27,
  112,
  3,
  7,
  318,
  6,
  130,
  10,
  47,
  400,
  3,
  143,
  413,
  157,
  385,
  130,
  157,
  102,
  130,
  4,
  157,
  632,
  17,
  56,
  54,
  47,
  23,
  112,
  157,
  3540,
  329,
  30,
  47,
  171,
  3,
  202,
  2407,
  30,
  47,
  171,
  3,
  928,
  4,
  598,
  130,
  30,
  1547,
  14,
  34,
  39,
  226,
  30,
  34,
  5,
  39,
  2,
  13,
  119,
  59,
  294,
  3541,
  157,
  721,
  20,
  541,
  67,
  31,
  1297,
  10,
  5,
  294,
  17,
  3],
 [30,
  15,
  1548,
  275,
  203,
  95,
  123,
  9,
  40,
  185,
  274,
  1,
  111,
  2,
  58,
  15,
  349,
  122,
  10,
  8,
  5,
  100,
  28,
  270,
  6,
  542,
  780,
  1549,
  32,
  1859,
  18,
  929,
  238,
  2,
  599,
  40,
  352,
  4,
  568,
  40,
  1026,
  26,
  7,
  1298,
  4,
  2408,
  444,
  1,
  673,
  28,
  23,
  13,
  724,
  26,
  58,
  9,
  7,
  162,
  6,
  848,
  32,
  1550,
  28,
  23,
  319,
  26,
  58,
  9,
  78,
  930,
  6,
  931,
  4,
  3542,
  28,
  23,
  2409,
  14,
  460,
  14,
  3543,
  14,
  1027,
  4,
  252,
  26,
  58,
  1,
  276,
  6,
  40,
  3544,
  10,
  5,
  7,
  673,
  28,
  1860],
 [3,
  147,
  76,
  12,
  21,
  17,
  94,
  36,
  261,
  339,
  2,
  25,
  569,
  92,
  17,
  3,
  91,
  22,
  8,
  1299,
  118,
  36,
  3,
  39],
 [3545, 305, 2410, 52, 456],
 [30,
  11,
  848,
  11,
  200,
  10,
  24,
  145,
  456,
  1,
  71,
  6,
  213,
  4,
  39,
  18,
  67,
  849,
  34,
  18,
  116,
  3546,
  4,
  3547,
  4,
  17,
  7,
  66,
  33,
  23,
  1028,
  3548,
  20,
  9,
  1,
  166,
  33,
  67,
  243,
  79,
  6,
  3549],
 [51, 15, 1300, 37, 1301, 340, 1, 2411, 3550, 177, 3551, 103, 1, 233],
 [97, 5, 500, 1, 428, 445, 480, 161, 306],
 [11,
  147,
  112,
  3,
  7,
  3552,
  1551,
  17,
  322,
  20,
  11,
  23,
  112,
  3,
  7,
  1551,
  17,
  337,
  184,
  2,
  1302,
  481,
  24,
  1,
  66],
 [25, 19, 3, 128, 9, 12, 87, 2, 13, 92, 600, 17, 932, 13, 3553, 669],
 [1,
  45,
  36,
  17,
  46,
  16,
  1,
  928,
  229,
  1,
  229,
  28,
  16,
  928,
  2,
  76,
  928,
  2,
  461,
  928,
  2,
  13,
  1552,
  3554,
  6,
  104,
  44,
  1,
  154,
  66,
  1,
  229,
  28,
  43,
  3555,
  32,
  126,
  7,
  3556,
  86,
  20,
  633,
  633,
  633,
  55,
  1543,
  1861,
  2412,
  3557,
  3558,
  55,
  3559,
  781,
  1,
  328,
  4,
  9,
  1,
  2413,
  3,
  80,
  1,
  850,
  3560,
  2414,
  4,
  481,
  566,
  3561],
 [165, 5, 14, 74, 462, 180, 8, 253, 65, 12, 75, 782],
 [281, 570, 26, 7, 329],
 [43,
  634,
  10,
  7,
  269,
  1862,
  6,
  3562,
  3563,
  1863,
  23,
  102,
  1,
  42,
  783,
  8,
  5,
  1,
  45,
  86,
  10,
  127,
  83],
 [25,
  14,
  266,
  29,
  350,
  25,
  2,
  3564,
  60,
  32,
  55,
  1,
  2415,
  17,
  1,
  307,
  6,
  3565,
  35,
  266,
  9,
  521,
  2,
  76],
 [2416,
  1,
  199,
  5,
  7,
  187,
  6,
  3566,
  3,
  501,
  12,
  292,
  21,
  3567,
  9,
  1,
  2417,
  338,
  68,
  64,
  247,
  851,
  8,
  31,
  90,
  4,
  64,
  2418,
  8,
  27,
  13,
  4,
  2416,
  10,
  199,
  725,
  3,
  120,
  20,
  3,
  43,
  25,
  8,
  3,
  70,
  442,
  1,
  199,
  2,
  851,
  1,
  346],
 [19,
  361,
  374,
  58,
  4,
  19,
  361,
  188,
  58,
  16,
  1029,
  482,
  1864,
  2,
  19,
  361,
  242,
  58],
 [17, 3568, 2419, 502, 262, 6, 386],
 [601, 1553],
 [674,
  5,
  3569,
  55,
  1303,
  55,
  411,
  8,
  83,
  35,
  1030,
  387,
  238,
  8,
  5,
  31,
  6,
  100,
  48,
  95,
  112,
  387,
  2,
  1030],
 [234, 3, 16, 13, 7, 101, 31],
 [11,
  208,
  1865,
  13,
  7,
  522,
  173,
  1,
  135,
  86,
  7,
  784,
  23,
  13,
  9,
  41,
  42,
  7,
  172,
  146,
  522],
 [196, 1304, 49, 52, 7, 92, 20, 33, 52, 7, 101, 1305],
 [220,
  33,
  1866,
  3,
  96,
  33,
  3570,
  3,
  4,
  96,
  33,
  1139,
  3,
  4,
  69,
  2,
  633,
  3,
  4,
  96,
  33,
  571,
  3571,
  2,
  3],
 [105, 3, 76, 85, 90, 6, 12, 21],
 [11,
  115,
  10,
  499,
  5,
  572,
  54,
  519,
  10,
  2420,
  5,
  56,
  1867,
  54,
  456,
  10,
  214,
  16,
  56,
  426,
  54,
  1306,
  10,
  208,
  67,
  2421,
  155,
  362,
  10,
  1307,
  5,
  1,
  45,
  2422,
  17,
  931,
  4,
  11,
  115,
  10,
  39,
  5,
  572,
  54,
  212],
 [28, 1554, 1, 233, 1554, 1, 199, 28, 1554, 1, 346, 1554, 1, 233],
 [3,
  147,
  319,
  9,
  12,
  1031,
  6,
  1,
  1555,
  341,
  17,
  109,
  2,
  121,
  2,
  3,
  3,
  18,
  2,
  81,
  2,
  57,
  158],
 [348, 8, 726, 2, 79, 10, 285, 5, 7, 178, 90, 26, 35, 287, 9, 8, 249],
 [22, 38, 21, 5, 120, 2, 274, 182, 11, 18, 2, 76, 8, 174],
 [3,
  23,
  461,
  26,
  131,
  17,
  244,
  1140,
  4,
  151,
  8,
  458,
  274,
  29,
  114,
  29,
  19,
  3,
  23,
  18,
  30,
  3,
  463,
  9,
  1141,
  6,
  131,
  14,
  543,
  7,
  428,
  249,
  3,
  128,
  10,
  123,
  26,
  12,
  87,
  3,
  128,
  55,
  3,
  18,
  573,
  1,
  123,
  17,
  373,
  2423,
  16,
  180,
  26,
  1,
  87,
  14,
  1,
  1868],
 [208, 5, 1, 86, 26, 3572],
 [4,
  181,
  1,
  933,
  5,
  155,
  3,
  1032,
  200,
  64,
  3,
  180,
  8,
  145,
  64,
  3,
  3573,
  2,
  1308,
  3,
  1032,
  91,
  13,
  401,
  271,
  1,
  933,
  5,
  159,
  155,
  20,
  31,
  86,
  5,
  852,
  30,
  3,
  121,
  73,
  6,
  1,
  933,
  3,
  1032,
  13,
  1,
  154,
  123,
  28,
  1033,
  9,
  503,
  19,
  41,
  3574,
  24,
  68],
 [30,
  11,
  63,
  2424,
  244,
  353,
  38,
  523,
  67,
  429,
  46,
  10,
  165,
  63,
  1,
  727,
  2,
  21,
  30,
  11,
  1142,
  2,
  675,
  33,
  544,
  46,
  19,
  11,
  728,
  2,
  13,
  30,
  11,
  1309,
  62,
  11,
  1034,
  163,
  3575,
  33,
  429,
  46,
  11,
  785,
  282,
  1,
  3576,
  4,
  11,
  429,
  57,
  33,
  785,
  282,
  21],
 [67, 25, 19, 3, 16, 223, 2, 25],
 [352, 5, 1035, 446, 5, 2425],
 [40, 185, 342, 2, 166, 1, 90, 15, 140, 724, 68, 48, 10, 153],
 [22, 108, 676, 41],
 [34,
  5,
  934,
  165,
  483,
  935,
  9,
  1,
  42,
  34,
  5,
  45,
  1,
  2426,
  6,
  31,
  729,
  26,
  156,
  97,
  56,
  47,
  28,
  83,
  464,
  1,
  672,
  931,
  5,
  135,
  354,
  2,
  362,
  1556,
  165,
  15,
  106,
  18,
  464,
  19,
  8,
  5,
  2,
  198,
  3577,
  10,
  15,
  105,
  484,
  1,
  3578,
  6,
  21],
 [9, 1, 166, 15, 27, 200, 14, 1, 262, 6, 40, 730, 20, 1, 602, 6, 40, 347],
 [25,
  14,
  82,
  12,
  1036,
  81,
  73,
  1037,
  53,
  2427,
  1037,
  9,
  1,
  1310,
  3579,
  6,
  1,
  3580,
  1,
  3581,
  4,
  1,
  3582,
  25,
  14,
  82,
  1,
  936,
  9,
  12,
  224,
  2428,
  9,
  1311,
  1869,
  17,
  1,
  21,
  3,
  2429,
  4,
  18,
  43,
  116,
  354,
  2,
  295,
  1,
  42,
  3,
  485,
  23,
  13,
  849,
  8,
  1038,
  8,
  5,
  219,
  8,
  5,
  306,
  50,
  402],
 [731,
  2430,
  7,
  1870,
  35,
  31,
  168,
  23,
  786,
  1838,
  2430,
  7,
  1870,
  35,
  31,
  168,
  23,
  80],
 [8, 5, 51, 226, 2, 3583, 3, 363, 4, 96, 8, 5, 1, 2431, 3584, 86, 9, 1, 42],
 [1, 139, 5, 50, 75, 204, 4, 9, 445, 23, 52, 7, 635, 6, 677, 7, 677, 6, 635],
 [1312, 5, 1871, 78, 851, 65, 276, 50, 7, 71, 6, 732, 8],
 [341, 5, 937, 3585, 5, 937, 20, 14, 460, 95, 2, 25, 5, 1, 636, 187, 6, 446],
 [1,
  42,
  5,
  783,
  343,
  6,
  3586,
  4,
  9,
  8,
  34,
  16,
  175,
  447,
  1143,
  20,
  151,
  34,
  5,
  114,
  10,
  5,
  1144,
  4,
  246,
  9,
  24,
  1557,
  39,
  5,
  144,
  3587,
  26,
  931,
  8,
  787,
  545,
  1,
  335],
 [25,
  14,
  81,
  134,
  1,
  364,
  105,
  603,
  81,
  270,
  134,
  34,
  5,
  35,
  364,
  4,
  363,
  7,
  3588],
 [11, 23, 13, 788, 53, 19, 430, 2, 46, 20, 11, 1145, 2, 13, 3589, 53, 8],
 [43, 82, 12, 388, 6, 2432, 1872, 3, 65, 189, 19, 5, 92],
 [677, 5, 1039, 4, 24, 1, 3590, 16, 192],
 [22,
  3,
  147,
  504,
  96,
  365,
  22,
  3,
  147,
  365,
  96,
  324,
  22,
  3,
  147,
  324,
  96,
  1146,
  20,
  234,
  3,
  25,
  3,
  18,
  2,
  138,
  524,
  431],
 [8,
  5,
  14,
  1,
  3591,
  28,
  1291,
  14,
  1,
  89,
  28,
  1313,
  73,
  64,
  1,
  308,
  89,
  3592,
  32,
  134,
  1,
  3593,
  6,
  1147,
  143,
  18,
  210,
  57,
  113,
  1,
  1873,
  1040,
  2,
  1,
  89,
  28,
  5,
  539,
  9,
  1,
  1558,
  733,
  252,
  5,
  3594,
  53,
  853,
  4,
  2433,
  4,
  854,
  28,
  3595,
  3596,
  28,
  3597,
  28,
  253,
  375,
  186,
  4,
  186,
  59,
  34,
  5,
  35,
  678,
  132,
  1559,
  4,
  2434,
  20,
  28,
  142,
  539,
  1148,
  2,
  25,
  1,
  1147,
  28,
  400,
  124,
  3598,
  1,
  124,
  3599,
  28,
  3600,
  330,
  9,
  7,
  637,
  638,
  28,
  44,
  1,
  135,
  400,
  9,
  1,
  166,
  1,
  1560,
  6,
  397,
  855,
  4,
  28,
  44,
  1,
  636,
  22,
  47,
  1561,
  44,
  360,
  1561,
  231,
  1874,
  2435,
  51,
  10,
  99,
  204,
  448,
  43,
  13,
  26,
  100,
  789,
  4,
  2436,
  679,
  28,
  934,
  61,
  604,
  483,
  938],
 [11,
  39,
  2,
  80,
  7,
  465,
  784,
  81,
  73,
  4,
  1149,
  1,
  42,
  53,
  1,
  3601,
  459,
  7,
  2437,
  261,
  339,
  2,
  81,
  73,
  4,
  1314,
  1562],
 [376, 12, 1026, 103, 790],
 [30, 3, 18, 3602, 24, 95, 5, 500, 96, 234, 1875, 546, 3603, 106, 13, 1, 213],
 [22, 3, 200, 46, 96, 11, 49, 245, 22, 217, 168, 2438],
 [734, 5, 281],
 [680,
  5,
  14,
  1315,
  8,
  5,
  7,
  1041,
  6,
  1,
  224,
  8,
  5,
  681,
  2439,
  6,
  229,
  1042,
  8,
  5,
  113,
  9,
  680,
  2,
  18,
  7,
  87,
  132,
  262,
  54,
  262,
  132,
  7,
  87],
 [791,
  5,
  7,
  296,
  165,
  5,
  7,
  296,
  2440,
  5,
  7,
  296,
  386,
  5,
  7,
  296,
  542,
  5,
  7,
  296,
  432,
  5,
  7,
  296,
  234,
  296,
  3,
  52,
  171,
  3,
  240,
  1876],
 [8,
  348,
  19,
  3,
  18,
  32,
  28,
  3,
  16,
  32,
  134,
  3,
  16,
  32,
  19,
  3,
  16,
  189,
  10,
  171,
  3,
  202,
  32,
  735,
  8,
  5,
  19,
  3,
  79,
  68,
  8],
 [19,
  11,
  129,
  5,
  1,
  3604,
  9,
  1,
  1043,
  1,
  1877,
  1861,
  10,
  227,
  3605,
  270,
  6,
  3606,
  1,
  601,
  10,
  21,
  23,
  81,
  37,
  35,
  153,
  64,
  331,
  40,
  3607,
  10,
  8,
  23,
  13,
  101,
  186],
 [4, 9, 1, 1878],
 [1, 199, 1040, 2, 100, 28, 115, 9, 1, 222, 6, 72, 214],
 [11,
  49,
  403,
  36,
  28,
  49,
  39,
  404,
  4,
  193,
  46,
  11,
  39,
  3,
  34,
  5,
  78,
  3608,
  543,
  95,
  5,
  13,
  1150,
  30,
  7,
  1044,
  123,
  2441,
  3,
  7,
  3609],
 [11,
  55,
  215,
  11,
  18,
  158,
  116,
  2442,
  3610,
  3611,
  939,
  3612,
  26,
  792,
  20,
  145,
  8,
  24,
  11,
  151,
  61,
  574,
  1563,
  10,
  70,
  2,
  13,
  263,
  5,
  7,
  1564,
  86],
 [11,
  84,
  14,
  401,
  525,
  19,
  635,
  27,
  13,
  55,
  20,
  11,
  61,
  10,
  30,
  15,
  198,
  4,
  8,
  253,
  66,
  17,
  98,
  2,
  605,
  58,
  47,
  27,
  14,
  275,
  64,
  175,
  101,
  48,
  18,
  3,
  210,
  9,
  12,
  21,
  238,
  47,
  27,
  275,
  64,
  114,
  39,
  254,
  3,
  258,
  103,
  19,
  3,
  254],
 [793,
  24,
  856,
  10,
  575,
  123,
  28,
  5,
  92,
  17,
  58,
  20,
  22,
  940,
  116,
  145,
  141,
  736,
  3,
  342,
  2,
  3613,
  541,
  35,
  92,
  123,
  70,
  230,
  3614,
  6,
  218,
  201,
  5,
  41,
  59,
  3,
  60,
  16,
  218,
  9,
  118,
  71,
  4,
  3,
  449,
  73,
  3615,
  28,
  16,
  218,
  9,
  118,
  3616,
  71,
  20,
  8,
  309,
  7,
  433,
  6,
  215,
  2,
  288,
  1045,
  103,
  12,
  75,
  3617,
  4,
  8,
  1296,
  225,
  3,
  941,
  365,
  62,
  340,
  12,
  672,
  3618,
  12,
  2443,
  3619,
  229,
  10,
  52,
  3,
  377,
  28,
  3,
  3620,
  793,
  462,
  2,
  122,
  7,
  3621,
  3622,
  45,
  96,
  25,
  3,
  941,
  61,
  19,
  378,
  315,
  17,
  378,
  315,
  17,
  1,
  218,
  123,
  20,
  14,
  70,
  160,
  218,
  123,
  50,
  339,
  2,
  13,
  1,
  92,
  218,
  3623,
  3,
  3624,
  2444,
  239,
  4,
  79,
  1879,
  5,
  1,
  486,
  11,
  69,
  2,
  18],
 [11,
  25,
  14,
  183,
  212,
  11,
  119,
  116,
  547,
  17,
  1880,
  4,
  1880,
  6,
  244,
  188,
  11,
  63,
  351,
  4,
  119,
  14,
  2445,
  1,
  1881,
  3625,
  65,
  8],
 [49, 605, 148, 90, 53, 1, 3626, 3, 1882, 20, 53, 1, 1316, 10, 3, 1317],
 [20, 11, 61, 1318, 10, 45, 30, 8, 5, 447, 141, 23, 3, 80, 1, 328],
 [639, 20, 203, 23, 264, 40, 576],
 [49, 13, 1565, 209, 53, 1, 640, 9, 12, 139, 13, 1883, 53, 1, 214, 9, 12, 87],
 [158,
  40,
  191,
  566,
  73,
  20,
  5,
  1566,
  186,
  103,
  1319,
  1320,
  53,
  78,
  1321,
  26,
  156,
  152,
  88],
 [2446, 526, 682],
 [1,
  213,
  5,
  355,
  3,
  82,
  81,
  355,
  3,
  389,
  60,
  355,
  3,
  389,
  1,
  641,
  355,
  3,
  366,
  10,
  1,
  641,
  5,
  155,
  3,
  150,
  527,
  431],
 [942,
  121,
  3627,
  103,
  38,
  21,
  35,
  466,
  2,
  794,
  683,
  32,
  2447,
  933,
  20,
  2,
  1151,
  857,
  2,
  38,
  2448,
  416],
 [36, 126, 97, 5, 500, 20, 11, 25, 97, 85, 90],
 [270, 6, 684, 68, 19, 3, 150, 356, 2449, 12, 1152, 2, 19, 3, 23, 417],
 [7,
  1884,
  87,
  125,
  13,
  51,
  1046,
  9,
  98,
  10,
  7,
  89,
  83,
  2,
  449,
  130,
  70,
  2,
  122,
  164],
 [50, 187, 6, 1153, 2, 25, 1, 500],
 [1,
  48,
  3,
  25,
  17,
  60,
  16,
  487,
  30,
  3,
  16,
  487,
  20,
  1,
  48,
  3,
  25,
  17,
  109,
  642,
  29,
  12,
  3628],
 [7,
  3629,
  125,
  342,
  85,
  2450,
  26,
  7,
  1885,
  6,
  505,
  59,
  24,
  48,
  9,
  405,
  16,
  447,
  795,
  134,
  1567,
  53,
  1,
  191],
 [643, 2, 1322],
 [352, 5, 1568, 3630, 2451, 373],
 [30,
  11,
  63,
  7,
  146,
  784,
  11,
  450,
  2,
  266,
  1135,
  1539,
  9,
  1135,
  1539,
  3,
  379,
  1154,
  2452,
  4,
  685,
  104,
  3,
  127,
  728,
  9,
  1135,
  1539,
  1,
  331,
  1297,
  5,
  232,
  297,
  2,
  1886,
  1,
  331,
  1297,
  5,
  67,
  2453,
  7,
  505,
  2454,
  51,
  3,
  67,
  61,
  28,
  47,
  5,
  96,
  3,
  288,
  62,
  4,
  3,
  366,
  10,
  1154,
  2452,
  5,
  14,
  29,
  297,
  2,
  122,
  29,
  3,
  194,
  3,
  366,
  1,
  331,
  1297,
  5,
  14,
  2453,
  7,
  505,
  2454,
  4,
  685,
  14,
  297,
  2,
  1886,
  685,
  159,
  858,
  4,
  47,
  171,
  3,
  567,
  4,
  47,
  83,
  294,
  1047],
 [197,
  45,
  205,
  940,
  3631,
  488,
  12,
  577,
  859,
  10,
  3,
  342,
  2,
  102,
  288,
  4,
  2455],
 [1,
  111,
  190,
  187,
  6,
  489,
  5,
  2,
  13,
  19,
  3,
  159,
  16,
  3,
  2456,
  9,
  12,
  276,
  17,
  7,
  1323,
  3,
  2456,
  9,
  12,
  388,
  17,
  78,
  257,
  3,
  112,
  62,
  12,
  606,
  2,
  128,
  4,
  9,
  3632,
  258,
  37,
  7,
  3633,
  34,
  147,
  13,
  160,
  3634,
  943,
  225,
  284,
  7,
  686,
  943,
  37,
  78,
  860,
  1155,
  50,
  339,
  2,
  304,
  321,
  220],
 [49,
  13,
  223,
  6,
  12,
  640,
  412,
  14,
  34,

In [33]:
df["quote_tokens"] = tokenizer.texts_to_sequences(quote)

In [34]:
df

,index,quote,author,tags,likes,quote_tokens
0,0,Be yourself; everyone else is already taken.,Oscar Wilde,attributed-no-source;be-yourself;honesty;inspi...,149270,"[13, 60, 217, 168, 5, 518, 719]"
1,1,You've gotta dance like there's nobody watching,William W. Purkey,dance;heaven;hurt;inspirational;life;love;sing,118888,"[261, 846, 396, 55, 284, 497, 1133]"
2,2,Be the change that you wish to see in the world.,Mahatma Gandhi,action;change;inspirational;philosophy;wish,106749,"[13, 1, 102, 10, 3, 327, 2, 80, 9, 1, 42]"
3,3,No one can make you feel inferior without your...,"Eleanor Roosevelt,",confidence;inspirational;wisdom,85854,"[35, 31, 23, 52, 3, 128, 3515, 132, 12, 2393]"
4,4,Live as if you were to die tomorrow. Learn as ...,Mahatma Gandhi,carpe-diem;education;inspirational;learning,73033,"[76, 29, 22, 3, 93, 2, 198, 285, 136, 29, 22, ..."
...,...,...,...,...,...,...
2996,2996,And this is for Colored girls who have conside...,"Ntozake Shange,",inspirational,63,"[4, 41, 5, 17, 3489, 1287, 28, 18, 1255, 1491,..."
2997,2997,"After all, when you come right down to it, how...",Russell Hoban,inspirational,61,"[205, 24, 30, 3, 121, 92, 163, 2, 8, 64, 175, ..."
2998,2998,Aku telah mengidap sakit gila nomor enam belas...,"Andrea Hirata,",humor;inspirational;irony,61,"[2892, 7732, 7733, 7734, 7735, 7736, 7737, 773..."
2999,2999,The moon is the reflection of your heart and m...,Debasish Mridha,education;happiness;heart;hope;inspirational;i...,58,"[1, 1185, 5, 1, 1085, 6, 12, 87, 4, 7751, 5, 1..."
3000,186392,"But in the end it's only a passing thing, this...","J.R.R. Tolkien,",inspirational,161,"[20, 9, 1, 166, 50, 45, 7, 815, 86, 41, 974, 9..."

In [68]:
X = []
y = []
y1=[]
for sequence in df["quote_tokens"]:

    for i in range(1, len(sequence)):

        X.append(sequence[:i])
        y.append(sequence[i])
        y1.append(sequence[i])

In [36]:
print(X[:5])
print(y[:5])

[[13], [13, 60], [13, 60, 217], [13, 60, 217, 168], [13, 60, 217, 168, 5]]
[60, 217, 168, 5, 518]

In [69]:
y1

[60,
 217,
 168,
 5,
 518,
 719,
 846,
 396,
 55,
 284,
 497,
 1133,
 1,
 102,
 10,
 3,
 327,
 2,
 80,
 9,
 1,
 42,
 31,
 23,
 52,
 3,
 128,
 3515,
 132,
 12,
 2393,
 29,
 22,
 3,
 93,
 2,
 198,
 285,
 136,
 29,
 22,
 3,
 93,
 2,
 76,
 373,
 150,
 921,
 73,
 359,
 45,
 191,
 23,
 25,
 10,
 313,
 150,
 921,
 73,
 313,
 45,
 39,
 23,
 25,
 10,
 439,
 21,
 117,
 13,
 7,
 537,
 314,
 1,
 39,
 15,
 79,
 15,
 720,
 5,
 222,
 1134,
 5,
 1838,
 4,
 50,
 113,
 2,
 13,
 1537,
 1839,
 54,
 1537,
 1538,
 16,
 45,
 196,
 478,
 2,
 76,
 12,
 21,
 31,
 5,
 29,
 246,
 97,
 5,
 7,
 922,
 1,
 94,
 5,
 29,
 246,
 104,
 5,
 7,
 922,
 16,
 24,
 9,
 1,
 3516,
 20,
 118,
 6,
 58,
 16,
 315,
 44,
 1,
 328,
 1539,
 16,
 56,
 54,
 169,
 14,
 59,
 33,
 193,
 58,
 10,
 1281,
 721,
 20,
 59,
 33,
 193,
 58,
 10,
 1281,
 23,
 13,
 1840,
 5,
 456,
 285,
 5,
 7,
 1020,
 170,
 5,
 7,
 291,
 6,
 98,
 95,
 5,
 201,
 15,
 457,
 8,
 1,
 346,
 18,
 14,
 1282,
 316,
 70,
 334,
 3517,
 478,
 10,
 458,
 149,
 1021,
 6,
 39,
 5,
 14,
 313,
 50,
 1283,
 1,
 1021,
 6,
 411,
 5,
 14,
 3518,
 50,
 1283,
 1,
 1021,
 6,
 302,
 5,
 14,
 3519,
 50,
 1283,
 4,
 1,
 1021,
 6,
 21,
 5,
 14,
 212,
 50,
 1283,
 84,
 141,
 6,
 78,
 1284,
 2,
 1285,
 2394,
 239,
 38,
 499,
 499,
 5,
 56,
 190,
 54,
 519,
 519,
 5,
 1540,
 499,
 3520,
 1,
 42,
 18,
 1286,
 9,
 12,
 286,
 3,
 18,
 479,
 9,
 12,
 1022,
 3,
 23,
 2395,
 60,
 160,
 668,
 3,
 240,
 108,
 37,
 12,
 75,
 4,
 3,
 61,
 19,
 3,
 61,
 4,
 3,
 16,
 1,
 31,
 3521,
 538,
 134,
 2,
 81,
 5,
 43,
 137,
 1841,
 2,
 13,
 19,
 3,
 317,
 18,
 116,
 21,
 5,
 19,
 3,
 52,
 8,
 35,
 153,
 19,
 108,
 120,
 2,
 923,
 62,
 158,
 50,
 7,
 1842,
 213,
 20,
 1,
 101,
 318,
 5,
 3,
 77,
 2,
 538,
 64,
 108,
 120,
 2,
 923,
 8,
 62,
 1287,
 27,
 13,
 12,
 347,
 1843,
 257,
 55,
 8,
 669,
 20,
 70,
 200,
 118,
 121,
 118,
 81,
 1,
 229,
 10,
 319,
 26,
 3,
 145,
 104,
 412,
 12,
 169,
 135,
 347,
 49,
 82,
 81,
 6,
 57,
 303,
 200,
 1844,
 52,
 1,
 135,
 347,
 9,
 1,
 42,
 29,
 17,
 2396,
 207,
 1843,
 121,
 4,
 81,
 137,
 4,
 3522,
 11,
 313,
 2,
 126,
 8,
 111,
 6,
 57,
 539,
 1023,
 114,
 24,
 6,
 57,
 16,
 120,
 2,
 413,
 12,
 87,
 20,
 3,
 147,
 112,
 62,
 59,
 22,
 3,
 112,
 62,
 247,
 43,
 122,
 12,
 3523,
 247,
 43,
 122,
 10,
 629,
 28,
 171,
 3,
 292,
 4,
 10,
 566,
 17,
 104,
 70,
 59,
 3,
 440,
 181,
 241,
 274,
 108,
 924,
 440,
 44,
 104,
 138,
 248,
 320,
 37,
 4,
 67,
 67,
 67,
 115,
 9,
 60,
 59,
 22,
 3,
 49,
 96,
 28,
 27,
 3524,
 51,
 138,
 12,
 286,
 397,
 138,
 12,
 1845,
 62,
 4,
 111,
 2397,
 138,
 925,
 59,
 459,
 7,
 172,
 86,
 4,
 284,
 51,
 114,
 2,
 329,
 68,
 5,
 35,
 335,
 1541,
 54,
 2398,
 78,
 2399,
 414,
 321,
 3,
 3,
 23,
 779,
 5,
 219,
 23,
 43,
 77,
 7,
 1846,
 6,
 2400,
 1847,
 141,
 32,
 7,
 398,
 176,
 141,
 2,
 1848,
 46,
 1,
 3525,
 139,
 212,
 5,
 20,
 1,
 540,
 124,
 596,
 348,
 68,
 670,
 60,
 21,
 5,
 68,
 1288,
 60,
 19,
 3,
 23,
 26,
 19,
 3,
 18,
 134,
 3,
 16,
 2,
 1,
 3526,
 336,
 280,
 2,
 1,
 3527,
 280,
 2,
 1,
 3528,
 1,
 3529,
 1,
 3530,
 280,
 2,
 1,
 43,
 3531,
 96,
 280,
 630,
 2,
 46,
 182,
 23,
 304,
 336,
 182,
 23,
 13,
 31,
 722,
 6,
 165,
 2401,
 156,
 2402,
 20,
 349,
 15,
 133,
 51,
 176,
 44,
 1,
 1289,
 722,
 10,
 15,
 25,
 14,
 80,
 1,
 31,
 95,
 83,
 116,
 1290,
 17,
 58,
 5,
 14,
 1024,
 337,
 5,
 14,
 3532,
 8,
 5,
 1,
 237,
 2,
 1025,
 10,
 1291,
 41,
 5,
 38,
 21,
 4,
 11,
 69,
 3,
 2,
 61,
 10,
 11,
 84,
 520,
 202,
 4,
 671,
 4,
 161,
 151,
 248,
 2,
 2403,
 73,
 64,
 10,
 143,
 13,
 105,
 126,
 161,
 7,
 1136,
 20,
 161,
 14,
 1,
 45,
 31,
 11,
 208,
 926,
 247,
 1849,
 58,
 4,
 1,
 42,
 27,
 76,
 29,
 31,
 30,
 3,
 69,
 74,
 24,
 1,
 293,
 2404,
 9,
 927,
 3,
 2,
 415,
 8,
 672,
 183,
 5,
 14,
 10,
 15,
 16,
 1850,
 40,
 672,
 183,
 5,
 10,
 15,
 16,
 426,
 323,
 847,
 8,
 5,
 40,
 191,
 14,
 40,
 359,
 10,
 111,
 1851,
 58,
 15,
 275,
 203,
 28,
 84,
 11,
 2,
 13,
 1852,
 1542,
 1137,
 1543,
 539,
 28,
 16,
 3,
 14,
 2,
 13,
 3,
 16,
 7,
 336,
 6,
 98,
 12,
 1853,
 269,
 142,
 14,
 723,
 1,
 42,
 34,
 5,
 97,
 2405,
 68,
 3533,
 51,
 10,
 94,
 36,
 458,
 128,
 1854,
 209,
 3,
 15,
 16,
 24,
 441,
 2,
 597,
 29,
 350,
 25,
 15,
 93,
 351,
 2,
 52,
 2406,
 1,
 1292,
 6,
 98,
 10,
 5,
 242,
 58,
 50,
 14,
 70,
 9,
 118,
 6,
 58,
 50,
 9,
 217,
 4,
 29,
 15,
 82,
 40,
 75,
 191,
 597,
 15,
 3534,
 112,
 94,
 36,
 1544,
 2,
 25,
 1,
 154,
 29,
 15,
 16,
 3535,
 65,
 40,
 75,
 183,
 40,
 1545,
 3536,
 1855,
 109,
 35,
 442,
 120,
 177,
 2,
 498,
 59,
 11,
 63,
 7,
 230,
 123,
 96,
 108,
 1138,
 2,
 25,
 30,
 3,
 49,
 55,
 7,
 86,
 5,
 102,
 8,
 22,
 3,
 147,
 102,
 8,
 102,
 1,
 71,
 3,
 79,
 68,
 8,
 49,
 1546,
 1,
 1293,
 6,
 427,
 7,
 179,
 121,
 169,
 10,
 171,
 21,
 1294,
 631,
 7,
 123,
 35,
 153,
 64,
 269,
 14,
 294,
 3,
 3537,
 443,
 4,
 1,
 196,
 6,
 3,
 27,
 43,
 13,
 294,
 20,
 22,
 47,
 23,
 52,
 3,
 567,
 44,
 360,
 181,
 1856,
 3,
 2,
 79,
 1857,
 4,
 22,
 47,
 3538,
 2,
 88,
 152,
 4,
 399,
 287,
 320,
 1295,
 130,
 4,
 112,
 130,
 1,
 111,
 3,
 23,
 47,
 1296,
 120,
 2,
 3539,
 1858,
 1547,
 14,
 338,
 68,
 3,
 85,
 162,
 20,
 47,
 27,
 112,
 3,
 7,
 318,
 6,
 130,
 10,
 47,
 400,
 3,
 143,
 413,
 157,
 385,
 130,
 157,
 102,
 130,
 4,
 157,
 632,
 17,
 56,
 54,
 47,
 23,
 112,
 157,
 3540,
 329,
 30,
 47,
 171,
 3,
 202,
 2407,
 ...]

In [41]:
X

[[13],
 [13, 60],
 [13, 60, 217],
 [13, 60, 217, 168],
 [13, 60, 217, 168, 5],
 [13, 60, 217, 168, 5, 518],
 [261],
 [261, 846],
 [261, 846, 396],
 [261, 846, 396, 55],
 [261, 846, 396, 55, 284],
 [261, 846, 396, 55, 284, 497],
 [13],
 [13, 1],
 [13, 1, 102],
 [13, 1, 102, 10],
 [13, 1, 102, 10, 3],
 [13, 1, 102, 10, 3, 327],
 [13, 1, 102, 10, 3, 327, 2],
 [13, 1, 102, 10, 3, 327, 2, 80],
 [13, 1, 102, 10, 3, 327, 2, 80, 9],
 [13, 1, 102, 10, 3, 327, 2, 80, 9, 1],
 [35],
 [35, 31],
 [35, 31, 23],
 [35, 31, 23, 52],
 [35, 31, 23, 52, 3],
 [35, 31, 23, 52, 3, 128],
 [35, 31, 23, 52, 3, 128, 3515],
 [35, 31, 23, 52, 3, 128, 3515, 132],
 [35, 31, 23, 52, 3, 128, 3515, 132, 12],
 [76],
 [76, 29],
 [76, 29, 22],
 [76, 29, 22, 3],
 [76, 29, 22, 3, 93],
 [76, 29, 22, 3, 93, 2],
 [76, 29, 22, 3, 93, 2, 198],
 [76, 29, 22, 3, 93, 2, 198, 285],
 [76, 29, 22, 3, 93, 2, 198, 285, 136],
 [76, 29, 22, 3, 93, 2, 198, 285, 136, 29],
 [76, 29, 22, 3, 93, 2, 198, 285, 136, 29, 22],
 [76, 29, 22, 3, 93, 2, 198, 285, 136, 29, 22, 3],
 [76, 29, 22, 3, 93, 2, 198, 285, 136, 29, 22, 3, 93],
 [76, 29, 22, 3, 93, 2, 198, 285, 136, 29, 22, 3, 93, 2],
 [76, 29, 22, 3, 93, 2, 198, 285, 136, 29, 22, 3, 93, 2, 76],
 [359],
 [359, 150],
 [359, 150, 921],
 [359, 150, 921, 73],
 [359, 150, 921, 73, 359],
 [359, 150, 921, 73, 359, 45],
 [359, 150, 921, 73, 359, 45, 191],
 [359, 150, 921, 73, 359, 45, 191, 23],
 [359, 150, 921, 73, 359, 45, 191, 23, 25],
 [359, 150, 921, 73, 359, 45, 191, 23, 25, 10],
 [359, 150, 921, 73, 359, 45, 191, 23, 25, 10, 313],
 [359, 150, 921, 73, 359, 45, 191, 23, 25, 10, 313, 150],
 [359, 150, 921, 73, 359, 45, 191, 23, 25, 10, 313, 150, 921],
 [359, 150, 921, 73, 359, 45, 191, 23, 25, 10, 313, 150, 921, 73],
 [359, 150, 921, 73, 359, 45, 191, 23, 25, 10, 313, 150, 921, 73, 313],
 [359, 150, 921, 73, 359, 45, 191, 23, 25, 10, 313, 150, 921, 73, 313, 45],
 [359, 150, 921, 73, 359, 45, 191, 23, 25, 10, 313, 150, 921, 73, 313, 45, 39],
 [359,
  150,
  921,
  73,
  359,
  45,
  191,
  23,
  25,
  10,
  313,
  150,
  921,
  73,
  313,
  45,
  39,
  23],
 [359,
  150,
  921,
  73,
  359,
  45,
  191,
  23,
  25,
  10,
  313,
  150,
  921,
  73,
  313,
  45,
  39,
  23,
  25],
 [132],
 [132, 439],
 [132, 439, 21],
 [132, 439, 21, 117],
 [132, 439, 21, 117, 13],
 [132, 439, 21, 117, 13, 7],
 [15],
 [15, 314],
 [15, 314, 1],
 [15, 314, 1, 39],
 [15, 314, 1, 39, 15],
 [15, 314, 1, 39, 15, 79],
 [15, 314, 1, 39, 15, 79, 15],
 [1837],
 [1837, 5],
 [1837, 5, 222],
 [1837, 5, 222, 1134],
 [1837, 5, 222, 1134, 5],
 [1837, 5, 222, 1134, 5, 1838],
 [1837, 5, 222, 1134, 5, 1838, 4],
 [1837, 5, 222, 1134, 5, 1838, 4, 50],
 [1837, 5, 222, 1134, 5, 1838, 4, 50, 113],
 [1837, 5, 222, 1134, 5, 1838, 4, 50, 113, 2],
 [1837, 5, 222, 1134, 5, 1838, 4, 50, 113, 2, 13],
 [1837, 5, 222, 1134, 5, 1838, 4, 50, 113, 2, 13, 1537],
 [1837, 5, 222, 1134, 5, 1838, 4, 50, 113, 2, 13, 1537, 1839],
 [1837, 5, 222, 1134, 5, 1838, 4, 50, 113, 2, 13, 1537, 1839, 54],
 [1837, 5, 222, 1134, 5, 1838, 4, 50, 113, 2, 13, 1537, 1839, 54, 1537],
 [34],
 [34, 16],
 [34, 16, 45],
 [34, 16, 45, 196],
 [34, 16, 45, 196, 478],
 [34, 16, 45, 196, 478, 2],
 [34, 16, 45, 196, 478, 2, 76],
 [34, 16, 45, 196, 478, 2, 76, 12],
 [34, 16, 45, 196, 478, 2, 76, 12, 21],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31, 5],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31, 5, 29],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31, 5, 29, 246],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31, 5, 29, 246, 97],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31, 5, 29, 246, 97, 5],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31, 5, 29, 246, 97, 5, 7],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31, 5, 29, 246, 97, 5, 7, 922],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31, 5, 29, 246, 97, 5, 7, 922, 1],
 [34, 16, 45, 196, 478, 2, 76, 12, 21, 31, 5, 29, 246, 97, 5, 7, 922, 1, 94],
 [34,
  16,
  45,
  196,
  478,
  2,
  76,
  12,
  21,
  31,
  5,
  29,
  246,
  97,
  5,
  7,
  922,
  1,
  94,
  5],
 [34,
  16,
  45,
  196,
  478,
  2,
  76,
  12,
  21,
  31,
  5,
  29,
  246,
  97,
  5,
  7,
  922,
  1,
  94,
  5,
  29],
 [34,
  16,
  45,
  196,
  478,
  2,
  76,
  12,
  21,
  31,
  5,
  29,
  246,
  97,
  5,
  7,
  922,
  1,
  94,
  5,
  29,
  246],
 [34,
  16,
  45,
  196,
  478,
  2,
  76,
  12,
  21,
  31,
  5,
  29,
  246,
  97,
  5,
  7,
  922,
  1,
  94,
  5,
  29,
  246,
  104],
 [34,
  16,
  45,
  196,
  478,
  2,
  76,
  12,
  21,
  31,
  5,
  29,
  246,
  97,
  5,
  7,
  922,
  1,
  94,
  5,
  29,
  246,
  104,
  5],
 [34,
  16,
  45,
  196,
  478,
  2,
  76,
  12,
  21,
  31,
  5,
  29,
  246,
  97,
  5,
  7,
  922,
  1,
  94,
  5,
  29,
  246,
  104,
  5,
  7],
 [15],
 [15, 16],
 [15, 16, 24],
 [15, 16, 24, 9],
 [15, 16, 24, 9, 1],
 [15, 16, 24, 9, 1, 3516],
 [15, 16, 24, 9, 1, 3516, 20],
 [15, 16, 24, 9, 1, 3516, 20, 118],
 [15, 16, 24, 9, 1, 3516, 20, 118, 6],
 [15, 16, 24, 9, 1, 3516, 20, 118, 6, 58],
 [15, 16, 24, 9, 1, 3516, 20, 118, 6, 58, 16],
 [15, 16, 24, 9, 1, 3516, 20, 118, 6, 58, 16, 315],
 [15, 16, 24, 9, 1, 3516, 20, 118, 6, 58, 16, 315, 44],
 [15, 16, 24, 9, 1, 3516, 20, 118, 6, 58, 16, 315, 44, 1],
 [1135],
 [1135, 1539],
 [1135, 1539, 16],
 [1135, 1539, 16, 56],
 [1135, 1539, 16, 56, 54],
 [1135, 1539, 16, 56, 54, 169],
 [1135, 1539, 16, 56, 54, 169, 14],
 [1135, 1539, 16, 56, 54, 169, 14, 59],
 [1135, 1539, 16, 56, 54, 169, 14, 59, 33],
 [1135, 1539, 16, 56, 54, 169, 14, 59, 33, 193],
 [1135, 1539, 16, 56, 54, 169, 14, 59, 33, 193, 58],
 [1135, 1539, 16, 56, 54, 169, 14, 59, 33, 193, 58, 10],
 [1135, 1539, 16, 56, 54, 169, 14, 59, 33, 193, 58, 10, 1281],
 [1135, 1539, 16, 56, 54, 169, 14, 59, 33, 193, 58, 10, 1281, 721],
 [1135, 1539, 16, 56, 54, 169, 14, 59, 33, 193, 58, 10, 1281, 721, 20],
 [1135, 1539, 16, 56, 54, 169, 14, 59, 33, 193, 58, 10, 1281, 721, 20, 59],
 [1135, 1539, 16, 56, 54, 169, 14, 59, 33, 193, 58, 10, 1281, 721, 20, 59, 33],
 [1135,
  1539,
  16,
  56,
  54,
  169,
  14,
  59,
  33,
  193,
  58,
  10,
  1281,
  721,
  20,
  59,
  33,
  193],
 [1135,
  1539,
  16,
  56,
  54,
  169,
  14,
  59,
  33,
  193,
  58,
  10,
  1281,
  721,
  20,
  59,
  33,
  193,
  58],
 [1135,
  1539,
  16,
  56,
  54,
  169,
  14,
  59,
  33,
  193,
  58,
  10,
  1281,
  721,
  20,
  59,
  33,
  193,
  58,
  10],
 [1135,
  1539,
  16,
  56,
  54,
  169,
  14,
  59,
  33,
  193,
  58,
  10,
  1281,
  721,
  20,
  59,
  33,
  193,
  58,
  10,
  1281],
 [1135,
  1539,
  16,
  56,
  54,
  169,
  14,
  59,
  33,
  193,
  58,
  10,
  1281,
  721,
  20,
  59,
  33,
  193,
  58,
  10,
  1281,
  23],
 [1135,
  1539,
  16,
  56,
  54,
  169,
  14,
  59,
  33,
  193,
  58,
  10,
  1281,
  721,
  20,
  59,
  33,
  193,
  58,
  10,
  1281,
  23,
  13],
 [498],
 [498, 5],
 [498, 5, 456],
 [498, 5, 456, 285],
 [498, 5, 456, 285, 5],
 [498, 5, 456, 285, 5, 7],
 [498, 5, 456, 285, 5, 7, 1020],
 [498, 5, 456, 285, 5, 7, 1020, 170],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7, 291],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7, 291, 6],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7, 291, 6, 98],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7, 291, 6, 98, 95],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7, 291, 6, 98, 95, 5],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7, 291, 6, 98, 95, 5, 201],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7, 291, 6, 98, 95, 5, 201, 15],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7, 291, 6, 98, 95, 5, 201, 15, 457],
 [498, 5, 456, 285, 5, 7, 1020, 170, 5, 7, 291, 6, 98, 95, 5, 201, 15, 457, 8],
 [498,
  5,
  456,
  285,
  5,
  7,
  1020,
  170,
  5,
  7,
  291,
  6,
  98,
  95,
  5,
  201,
  15,
  457,
  8,
  1],
 [11],
 [11, 18],
 [11, 18, 14],
 [11, 18, 14, 1282],
 [11, 18, 14, 1282, 316],
 [11, 18, 14, 1282, 316, 70],
 [11, 18, 14, 1282, 316, 70, 334],
 [11, 18, 14, 1282, 316, 70, 334, 3517],
 [11, 18, 14, 1282, 316, 70, 334, 3517, 478],
 [11, 18, 14, 1282, 316, 70, 334, 3517, 478, 10],
 [11, 18, 14, 1282, 316, 70, 334, 3517, 478, 10, 458],
 [1],
 [1, 1021],
 [1, 1021, 6],
 [1, 1021, 6, 39],
 [1, 1021, 6, 39, 5],
 [1, 1021, 6, 39, 5, 14],
 [1, 1021, 6, 39, 5, 14, 313],
 [1, 1021, 6, 39, 5, 14, 313, 50],
 [1, 1021, 6, 39, 5, 14, 313, 50, 1283],
 [1, 1021, 6, 39, 5, 14, 313, 50, 1283, 1],
 [1, 1021, 6, 39, 5, 14, 313, 50, 1283, 1, 1021],
 [1, 1021, 6, 39, 5, 14, 313, 50, 1283, 1, 1021, 6],
 [1, 1021, 6, 39, 5, 14, 313, 50, 1283, 1, 1021, 6, 411],
 [1, 1021, 6, 39, 5, 14, 313, 50, 1283, 1, 1021, 6, 411, 5],
 [1, 1021, 6, 39, 5, 14, 313, 50, 1283, 1, 1021, 6, 411, 5, 14],
 [1, 1021, 6, 39, 5, 14, 313, 50, 1283, 1, 1021, 6, 411, 5, 14, 3518],
 [1, 1021, 6, 39, 5, 14, 313, 50, 1283, 1, 1021, 6, 411, 5, 14, 3518, 50],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4,
  1],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4,
  1,
  1021],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4,
  1,
  1021,
  6],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4,
  1,
  1021,
  6,
  21],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4,
  1,
  1021,
  6,
  21,
  5],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4,
  1,
  1021,
  6,
  21,
  5,
  14],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4,
  1,
  1021,
  6,
  21,
  5,
  14,
  212],
 [1,
  1021,
  6,
  39,
  5,
  14,
  313,
  50,
  1283,
  1,
  1021,
  6,
  411,
  5,
  14,
  3518,
  50,
  1283,
  1,
  1021,
  6,
  302,
  5,
  14,
  3519,
  50,
  1283,
  4,
  1,
  1021,
  6,
  21,
  5,
  14,
  212,
  50],
 [11],
 [11, 84],
 [11, 84, 141],
 [11, 84, 141, 6],
 [11, 84, 141, 6, 78],
 [11, 84, 141, 6, 78, 1284],
 [11, 84, 141, 6, 78, 1284, 2],
 [11, 84, 141, 6, 78, 1284, 2, 1285],
 [11, 84, 141, 6, 78, 1284, 2, 1285, 2394],
 [11, 84, 141, 6, 78, 1284, 2, 1285, 2394, 239],
 [11, 84, 141, 6, 78, 1284, 2, 1285, 2394, 239, 38],
 [11, 84, 141, 6, 78, 1284, 2, 1285, 2394, 239, 38, 499],
 [11, 84, 141, 6, 78, 1284, 2, 1285, 2394, 239, 38, 499, 499],
 [11, 84, 141, 6, 78, 1284, 2, 1285, 2394, 239, 38, 499, 499, 5],
 [11, 84, 141, 6, 78, 1284, 2, 1285, 2394, 239, 38, 499, 499, 5, 56],
 [11, 84, 141, 6, 78, 1284, 2, 1285, 2394, 239, 38, 499, 499, 5, 56, 190],
 [11, 84, 141, 6, 78, 1284, 2, 1285, 2394, 239, 38, 499, 499, 5, 56, 190, 54],
 [11,
  84,
  141,
  6,
  78,
  1284,
  2,
  1285,
  2394,
  239,
  38,
  499,
  499,
  5,
  56,
  190,
  54,
  519],
 [11,
  84,
  141,
  6,
  78,
  1284,
  2,
  1285,
  2394,
  239,
  38,
  499,
  499,
  5,
  56,
  190,
  54,
  519,
  519],
 [11,
  84,
  141,
  6,
  78,
  1284,
  2,
  1285,
  2394,
  239,
  38,
  499,
  499,
  5,
  56,
  190,
  54,
  519,
  519,
  5],
 [11,
  84,
  141,
  6,
  78,
  1284,
  2,
  1285,
  2394,
  239,
  38,
  499,
  499,
  5,
  56,
  190,
  54,
  519,
  519,
  5,
  1540],
 [11,
  84,
  141,
  6,
  78,
  1284,
  2,
  1285,
  2394,
  239,
  38,
  499,
  499,
  5,
  56,
  190,
  54,
  519,
  519,
  5,
  1540,
  499],
 [11,
  84,
  141,
  6,
  78,
  1284,
  2,
  1285,
  2394,
  239,
  38,
  499,
  499,
  5,
  56,
  190,
  54,
  519,
  519,
  5,
  1540,
  499,
  3520],
 [11,
  84,
  141,
  6,
  78,
  1284,
  2,
  1285,
  2394,
  239,
  38,
  499,
  499,
  5,
  56,
  190,
  54,
  519,
  519,
  5,
  1540,
  499,
  3520,
  1],
 [3],
 [3, 18],
 [3, 18, 1286],
 [3, 18, 1286, 9],
 [3, 18, 1286, 9, 12],
 [3, 18, 1286, 9, 12, 286],
 [3, 18, 1286, 9, 12, 286, 3],
 [3, 18, 1286, 9, 12, 286, 3, 18],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479, 9],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479, 9, 12],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479, 9, 12, 1022],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479, 9, 12, 1022, 3],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479, 9, 12, 1022, 3, 23],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479, 9, 12, 1022, 3, 23, 2395],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479, 9, 12, 1022, 3, 23, 2395, 60],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479, 9, 12, 1022, 3, 23, 2395, 60, 160],
 [3, 18, 1286, 9, 12, 286, 3, 18, 479, 9, 12, 1022, 3, 23, 2395, 60, 160, 668],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4,
  3],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4,
  3,
  16],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4,
  3,
  16,
  1],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4,
  3,
  16,
  1,
  31],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4,
  3,
  16,
  1,
  31,
  3521],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4,
  3,
  16,
  1,
  31,
  3521,
  538],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4,
  3,
  16,
  1,
  31,
  3521,
  538,
  134],
 [3,
  18,
  1286,
  9,
  12,
  286,
  3,
  18,
  479,
  9,
  12,
  1022,
  3,
  23,
  2395,
  60,
  160,
  668,
  3,
  240,
  108,
  37,
  12,
  75,
  4,
  3,
  61,
  19,
  3,
  61,
  4,
  3,
  16,
  1,
  31,
  3521,
  538,
  134,
  2],
 [8],
 [8, 5],
 [8, 5, 43],
 [8, 5, 43, 137],
 [8, 5, 43, 137, 1841],
 [8, 5, 43, 137, 1841, 2],
 [8, 5, 43, 137, 1841, 2, 13],
 [8, 5, 43, 137, 1841, 2, 13, 19],
 [8, 5, 43, 137, 1841, 2, 13, 19, 3],
 [8, 5, 43, 137, 1841, 2, 13, 19, 3, 317],
 [8, 5, 43, 137, 1841, 2, 13, 19, 3, 317, 18],
 [41],
 [41, 21],
 [41, 21, 5],
 [41, 21, 5, 19],
 [41, 21, 5, 19, 3],
 [41, 21, 5, 19, 3, 52],
 [41, 21, 5, 19, 3, 52, 8],
 [41, 21, 5, 19, 3, 52, 8, 35],
 [41, 21, 5, 19, 3, 52, 8, 35, 153],
 [41, 21, 5, 19, 3, 52, 8, 35, 153, 19],
 [41, 21, 5, 19, 3, 52, 8, 35, 153, 19, 108],
 [41, 21, 5, 19, 3, 52, 8, 35, 153, 19, 108, 120],
 [41, 21, 5, 19, 3, 52, 8, 35, 153, 19, 108, 120, 2],
 [41, 21, 5, 19, 3, 52, 8, 35, 153, 19, 108, 120, 2, 923],
 [41, 21, 5, 19, 3, 52, 8, 35, 153, 19, 108, 120, 2, 923, 62],
 [41, 21, 5, 19, 3, 52, 8, 35, 153, 19, 108, 120, 2, 923, 62, 158],
 [41, 21, 5, 19, 3, 52, 8, 35, 153, 19, 108, 120, 2, 923, 62, 158, 50],
 [41, 21, 5, 19, 3, 52, 8, 35, 153, 19, 108, 120, 2, 923, 62, 158, 50, 7],
 [41,
  21,
  5,
  19,
  3,
  52,
  8,
  35,
  153,
  19,
  108,
  120,
  2,
  923,
  62,
  158,
  50,
  7,
  1842],
 [41,
  21,
  5,
  19,
  3,
  52,
  8,
  35,
  153,
  19,
  108,
  120,
  2,
  923,
  62,
  158,
  50,
  7,
  1842,
  213],
 [41,
  21,
  5,
  19,
  3,
  52,
  8,
  35,
  153,
  19,
  108,
  120,
  2,
  923,
  62,
  158,
  50,
  7,
  1842,
  213,
  20],
 [41,
  21,
  5,
  19,
  3,
  52,
  8,
  35,
  153,
  19,
  108,
  120,
  2,
  923,
  62,
  158,
  50,
  7,
  1842,
  213,
  20,
  1],
 [41,
  21,
  5,
  19,
  3,
  52,
  8,
  35,
  153,
  19,
  108,
  120,
  2,
  923,
  62,
  158,
  50,
  7,
  1842,
  213,
  20,
  1,
  101],
 [41,
  21,
  5,
  19,
  3,
  52,
  8,
  35,
  153,
  19,
  108,
  120,
  2,
  923,
  62,
  158,
  50,
  7,
  1842,
  213,
  20,
  1,
  101,
  318],
 [41,
  21,
  5,
  19,
  3,
  52,
  8,
  35,

In [43]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X = pad_sequences(X, padding="pre")

In [44]:
X

array([[  0,   0,   0, ...,   0,   0,  13],
       [  0,   0,   0, ...,   0,  13,  60],
       [  0,   0,   0, ...,  13,  60, 217],
       ...,
       [  0,   0,   0, ...,  41, 974,  91],
       [  0,   0,   0, ..., 974,  91, 359],
       [  0,   0,   0, ...,  91, 359, 106]],
      shape=(79812, 287), dtype=int32)

In [45]:
y=np.array(y)

In [46]:
y

array([ 60, 217, 168, ..., 359, 106, 623], shape=(79812,))

In [47]:
X.shape

(79812, 287)

In [48]:
y.shape

(79812,)

In [57]:
vocab_size = len(tokenizer.word_index)

print("Maximum vocabulary:", vocab_size)

Maximum vocabulary: 7751

In [58]:
print(tokenizer.word_index)

{'the': 1, 'to': 2, 'you': 3, 'and': 4, 'is': 5, 'of': 6, 'a': 7, 'it': 8, 'in': 9, 'that': 10, 'i': 11, 'your': 12, 'be': 13, 'not': 14, 'we': 15, 'are': 16, 'for': 17, 'have': 18, 'what': 19, 'but': 20, 'life': 21, 'if': 22, 'can': 23, 'all': 24, 'do': 25, 'with': 26, 'will': 27, 'who': 28, 'as': 29, 'when': 30, 'one': 31, 'or': 32, 'they': 33, 'there': 34, 'no': 35, 'people': 36, 'on': 37, 'my': 38, 'love': 39, 'our': 40, 'this': 41, 'world': 42, 'never': 43, 'at': 44, 'only': 45, 'me': 46, 'he': 47, 'things': 48, 'dont': 49, 'its': 50, 'so': 51, 'make': 52, 'by': 53, 'than': 54, 'like': 55, 'more': 56, 'them': 57, 'us': 58, 'because': 59, 'yourself': 60, 'know': 61, 'up': 62, 'was': 63, 'how': 64, 'from': 65, 'time': 66, 'always': 67, 'about': 68, 'want': 69, 'just': 70, 'way': 71, 'their': 72, 'out': 73, 'something': 74, 'own': 75, 'live': 76, 'get': 77, 'an': 78, 'think': 79, 'see': 80, 'go': 81, 'let': 82, 'has': 83, 'am': 84, 'every': 85, 'thing': 86, 'heart': 87, 'being': 88, 'man': 89, 'day': 90, 'even': 91, 'right': 92, 'were': 93, 'other': 94, 'which': 95, 'then': 96, 'nothing': 97, 'god': 98, 'his': 99, 'those': 100, 'good': 101, 'change': 102, 'into': 103, 'everything': 104, 'may': 105, 'must': 106, 'she': 107, 'youre': 108, 'others': 109, 'take': 110, 'most': 111, 'give': 112, 'better': 113, 'much': 114, 'believe': 115, 'been': 116, 'would': 117, 'some': 118, 'had': 119, 'going': 120, 'come': 121, 'find': 122, 'person': 123, 'great': 124, 'should': 125, 'say': 126, 'ever': 127, 'feel': 128, 'need': 129, 'him': 130, 'someone': 131, 'without': 132, 'look': 133, 'where': 134, 'best': 135, 'learn': 136, 'too': 137, 'keep': 138, 'mind': 139, 'become': 140, 'enough': 141, 'does': 142, 'could': 143, 'now': 144, 'through': 145, 'little': 146, 'cant': 147, 'each': 148, 'work': 149, 'cannot': 150, 'still': 151, 'human': 152, 'matter': 153, 'same': 154, 'over': 155, 'another': 156, 'don’t': 157, 'sometimes': 158, 'really': 159, 'any': 160, 'im': 161, 'moment': 162, 'down': 163, 'her': 164, 'happiness': 165, 'end': 166, 'said': 167, 'else': 168, 'true': 169, 'today': 170, 'makes': 171, 'beautiful': 172, 'thats': 173, 'myself': 174, 'many': 175, 'long': 176, 'back': 177, 'new': 178, 'dream': 179, 'made': 180, 'once': 181, 'anything': 182, 'fear': 183, 'try': 184, 'lives': 185, 'again': 186, 'kind': 187, 'before': 188, 'doing': 189, 'important': 190, 'light': 191, 'here': 192, 'tell': 193, 'thought': 194, 'away': 195, 'two': 196, 'it’s': 197, 'die': 198, 'future': 199, 'remember': 200, 'why': 201, 'happy': 202, 'ourselves': 203, 'place': 204, 'after': 205, 'stop': 206, 'well': 207, 'hope': 208, 'around': 209, 'done': 210, 'power': 211, 'death': 212, 'truth': 213, 'dreams': 214, 'living': 215, 'lose': 216, 'everyone': 217, 'wrong': 218, 'real': 219, 'first': 220, 'these': 221, 'beauty': 222, 'afraid': 223, 'soul': 224, 'until': 225, 'hard': 226, 'means': 227, 'men': 228, 'ones': 229, 'different': 230, 'while': 231, 'very': 232, 'past': 233, 'whatever': 234, 'write': 235, 'stand': 236, 'courage': 237, 'rather': 238, 'upon': 239, 'choose': 240, 'doesnt': 241, 'within': 242, 'fall': 243, 'years': 244, 'care': 245, 'though': 246, 'youll': 247, 'trying': 248, 'yet': 249, 'eyes': 250, 'such': 251, 'face': 252, 'comes': 253, 'did': 254, 'alone': 255, 'times': 256, 'act': 257, 'put': 258, 'forget': 259, 'joy': 260, 'youve': 261, 'words': 262, 'alive': 263, 'free': 264, 'start': 265, 'read': 266, 'reason': 267, 'help': 268, 'small': 269, 'instead': 270, 'whether': 271, 'less': 272, 'greatest': 273, 'mean': 274, 'ask': 275, 'reality': 276, 'worth': 277, 'last': 278, 'strength': 279, 'listen': 280, 'peace': 281, 'understand': 282, 'wait': 283, 'theres': 284, 'tomorrow': 285, 'head': 286, 'mistakes': 287, 'grow': 288, 'open': 289, 'self': 290, 'gift': 291, 'whole': 292, 'universe': 293, 'perfect': 294, 'reach': 295, 'choice': 296, 'easy': 297, 'earth': 298, 'step': 299, 'anyone': 300, 'woman': 301, 'faith': 302, 'also': 303, 'happen': 304, 'women': 305, 'possible': 306, 'purpose': 307, 'strong': 308, 'takes': 309, 'loved': 310, 'moments': 311, 'far': 312, 'hate': 313, 'accept': 314, 'looking': 315, 'ive': 316, 'might': 317, 'part': 318, 'stay': 319, 'hold': 320, 'inside': 321, 'success': 322, 'beyond': 323, 'walk': 324, 'given': 325, 'maybe': 326, 'wish': 327, 'stars': 328, 'smile': 329, 'himself': 330, 'bad': 331, 'off': 332, 'broken': 333, 'found': 334, 'greater': 335, 'child': 336, 'failure': 337, 'thinking': 338, 'got': 339, 'against': 340, 'waiting': 341, 'begin': 342, 'full': 343, 'books': 344, 'thoughts': 345, 'present': 346, 'friends': 347, 'isnt': 348, 'often': 349, 'children': 350, 'born': 351, 'pain': 352, 'old': 353, 'able': 354, 'unless': 355, 'control': 356, 'difference': 357, 'fact': 358, 'darkness': 359, 'least': 360, 'lies': 361, 'experience': 362, 'leave': 363, 'path': 364, 'run': 365, 'realize': 366, 'feeling': 367, 'bring': 368, 'spirit': 369, 'lost': 370, 'deep': 371, 'road': 372, 'forever': 373, 'behind': 374, 'short': 375, 'turn': 376, 'truly': 377, 'you’re': 378, 'meet': 379, 'between': 380, 'few': 381, 'rest': 382, 'left': 383, 'yang': 384, 'hurt': 385, 'kindness': 386, 'value': 387, 'sense': 388, 'forgive': 389, 'hands': 390, 'positive': 391, 'beginning': 392, 'days': 393, 'gods': 394, 'fight': 395, 'dance': 396, 'high': 397, 'book': 398, 'making': 399, 'knows': 400, 'sure': 401, 'yours': 402, 'trust': 403, 'themselves': 404, 'nature': 405, 'hearts': 406, 'hear': 407, 'chance': 408, 'meaning': 409, 'together': 410, 'art': 411, 'theyre': 412, 'break': 413, 'story': 414, 'achieve': 415, 'sky': 416, 'create': 417, 'writing': 418, 'allow': 419, 'wings': 420, 'seen': 421, 'along': 422, 'save': 423, 'big': 424, 'play': 425, 'powerful': 426, 'having': 427, 'word': 428, 'told': 429, 'happens': 430, 'forward': 431, 'respect': 432, 'lot': 433, 'body': 434, 'knew': 435, 'lived': 436, 'answer': 437, 'sun': 438, 'music': 439, 'fail': 440, 'meant': 441, 'use': 442, 'either': 443, 'hand': 444, 'itself': 445, 'suffering': 446, 'dark': 447, 'shall': 448, 'seek': 449, 'used': 450, '—': 451, 'capable': 452, 'journey': 453, 'gives': 454, 'learned': 455, 'history': 456, 'call': 457, 'wont': 458, 'lifes': 459, 'knowing': 460, 'talk': 461, 'ready': 462, 'sit': 463, 'felt': 464, 'young': 465, 'longer': 466, 'water': 467, 'waste': 468, 'destiny': 469, 'follow': 470, 'can’t': 471, 'i’ve': 472, 'point': 473, 'getting': 474, 'gets': 475, 'name': 476, 'home': 477, 'ways': 478, 'feet': 479, 'says': 480, 'everybody': 481, 'matters': 482, 'nor': 483, 'appreciate': 484, 'desire': 485, 'problem': 486, 'gone': 487, 'outside': 488, 'freedom': 489, 'brave': 490, 'difficult': 491, 'doesn’t': 492, 'potential': 493, 'wise': 494, 'problems': 495, 'wing': 496, 'nobody': 497, 'yesterday': 498, 'imagination': 499, 'impossible': 500, 'spend': 501, 'speak': 502, 'that’s': 503, 'fly': 504, 'black': 505, 'stories': 506, 'didnt': 507, 'grateful': 508, 'becomes': 509, 'set': 510, 'money': 511, 'loving': 512, 'needs': 513, 'above': 514, 'night': 515, 'dan': 516, 'came': 517, 'already': 518, 'knowledge': 519, 'both': 520, 'order': 521, 'fool': 522, 'mother': 523, 'moving': 524, 'exactly': 525, 'patience': 526, 'move': 527, 'regret': 528, 'among': 529, 'show': 530, 'rich': 531, 'since': 532, 'three': 533, 'ill': 534, 'grace': 535, 'di': 536, 'mistake': 537, 'decide': 538, 'actually': 539, 'next': 540, 'there’s': 541, 'giving': 542, 'saying': 543, 'asked': 544, 'perhaps': 545, 'however': 546, 'dead': 547, 'single': 548, 'focus': 549, 'anger': 550, 'evil': 551, 'passion': 552, 'white': 553, 'question': 554, 'weak': 555, 'course': 556, 'action': 557, 'mans': 558, 'ordinary': 559, 'under': 560, 'travel': 561, 'feelings': 562, 'unique': 563, 'kids': 564, 'itu': 565, 'goes': 566, 'laugh': 567, 'touch': 568, 'whats': 569, 'begins': 570, 'build': 571, 'stronger': 572, 'known': 573, 'quite': 574, 'special': 575, 'minds': 576, 'comfort': 577, 'return': 578, 'changes': 579, 'victim': 580, 'id': 581, 'land': 582, 'called': 583, 'simply': 584, 'willing': 585, 'second': 586, 'plan': 587, 'existence': 588, 'risk': 589, 'rise': 590, 'choices': 591, 'ahead': 592, 'spiritual': 593, 'religion': 594, 'thou': 595, 'adventure': 596, 'shine': 597, 'miss': 598, 'share': 599, '–': 600, 'promise': 601, 'silence': 602, 'lead': 603, 'victory': 604, 'judge': 605, 'ability': 606, 'shes': 607, 'voice': 608, 'learning': 609, 'star': 610, 'ideas': 611, 'limit': 612, 'battle': 613, 'parents': 614, 'wonderful': 615, 'side': 616, 'opinion': 617, 'suffer': 618, 'i’m': 619, 'anymore': 620, 'wind': 621, 'air': 622, 'pass': 623, 'discover': 624, 'poor': 625, 'ground': 626, 'tree': 627, 'successful': 628, 'half': 629, 'close': 630, 'persons': 631, 'expect': 632, 'burn': 633, 'doubt': 634, 'heaven': 635, 'worst': 636, 'worthy': 637, 'cause': 638, 'none': 639, 'fears': 640, 'situation': 641, 'remain': 642, 'dare': 643, 'opportunity': 644, 'responsibility': 645, 'feels': 646, 'amazing': 647, 'planet': 648, 'letting': 649, 'inner': 650, 'sight': 651, 'circumstances': 652, 'written': 653, 'form': 654, 'heard': 655, 'lie': 656, 'higher': 657, 'false': 658, 'running': 659, 'morning': 660, 'memory': 661, 'challenge': 662, 'happened': 663, 'ada': 664, 'divine': 665, 'confidence': 666, 'ang': 667, 'direction': 668, 'anyway': 669, 'finding': 670, 'sad': 671, 'deepest': 672, 'friend': 673, 'friendship': 674, 'school': 675, 'reading': 676, 'hell': 677, 'effort': 678, 'souls': 679, 'prayer': 680, 'daily': 681, 'compassion': 682, 'rain': 683, 'worrying': 684, 'hes': 685, 'personal': 686, 'worry': 687, 'yes': 688, 'fighting': 689, 'soon': 690, 'trees': 691, 'bear': 692, 'wonder': 693, 'relationship': 694, 'telling': 695, 'fit': 696, 'win': 697, 'belong': 698, 'limitations': 699, 'coming': 700, 'teach': 701, 'angry': 702, 'street': 703, 'enjoy': 704, 'honest': 705, 'bit': 706, 'humanity': 707, 'stupid': 708, 'master': 709, 'almost': 710, 'idea': 711, 'perfection': 712, 'created': 713, 'thinks': 714, 'belief': 715, 'usually': 716, 'kamu': 717, 'cinta': 718, 'taken': 719, 'deserve': 720, 'exist': 721, 'door': 722, 'serve': 723, 'silent': 724, 'keeps': 725, 'nice': 726, 'key': 727, 'wanted': 728, 'state': 729, 'enemies': 730, 'talent': 731, 'understanding': 732, 'whose': 733, 'war': 734, 'unhappy': 735, 'relationships': 736, 'believed': 737, 'watch': 738, 'secret': 739, 'growing': 740, 'worse': 741, 'smart': 742, 'opinions': 743, 'goals': 744, 'sing': 745, 'decisions': 746, 'walking': 747, 'safe': 748, 'amount': 749, 'force': 750, 'express': 751, 'whom': 752, 'tears': 753, 'leaves': 754, 'kept': 755, 'terrible': 756, 'toward': 757, 'ends': 758, 'therefore': 759, 'forgotten': 760, 'arent': 761, 'awake': 762, 'apart': 763, 'accomplish': 764, 'negative': 765, 'room': 766, 'experiences': 767, 'lessons': 768, 'brain': 769, 'necessary': 770, 'somebody': 771, 'climb': 772, 'enemy': 773, 'fate': 774, 'changing': 775, 'sea': 776, 'decision': 777, 'akan': 778, 'imagine': 779, 'advice': 780, 'across': 781, 'actions': 782, 'indeed': 783, 'girl': 784, 'didn’t': 785, 'hit': 786, 'grows': 787, 'changed': 788, 'cold': 789, 'wisdom': 790, 'attitude': 791, 'sorrow': 792, 'we’re': 793, 'carry': 794, 'except': 795, 'recognize': 796, 'treat': 797, 'mountains': 798, 'somewhere': 799, 'common': 800, 'throw': 801, 'seems': 802, 'river': 803, 'lack': 804, 'harder': 805, 'opportunities': 806, 'offer': 807, 'walls': 808, 'skin': 809, 'character': 810, 'requires': 811, 'met': 812, 'year': 813, 'falls': 814, 'passing': 815, 'dangerous': 816, 'thousand': 817, 'wake': 818, 'benefit': 819, 'beings': 820, 'towards': 821, 'vast': 822, 'sa': 823, 'terms': 824, 'goal': 825, 'simple': 826, 'chaos': 827, 'talents': 828, 'taking': 829, 'taught': 830, 'miracles': 831, 'law': 832, 'song': 833, 'realized': 834, 'lord': 835, 'forgiveness': 836, 'christ': 837, 'generation': 838, 'distance': 839, 'o': 840, 'tried': 841, 'million': 842, 'science': 843, 'tidak': 844, 'kau': 845, 'gotta': 846, 'measure': 847, 'despair': 848, 'won': 849, 'blue': 850, 'escape': 851, 'certain': 852, 'dust': 853, 'blood': 854, 'achievement': 855, 'seeking': 856, 'color': 857, 'funny': 858, 'zone': 859, 'individual': 860, 'percent': 861, 'stuff': 862, 'rose': 863, 'helps': 864, 'house': 865, 'weve': 866, 'dog': 867, 'treasure': 868, 'define': 869, 'heal': 870, 'limits': 871, 'bird': 872, 'business': 873, 'jump': 874, 'youd': 875, 'difficulties': 876, 'believing': 877, 'infinite': 878, 'four': 879, 'shit': 880, 'elses': 881, 'depends': 882, 'dear': 883, 'minute': 884, 'eat': 885, 'lift': 886, 'lucky': 887, 'dying': 888, 'aim': 889, 'oneself': 890, 'clear': 891, 'merely': 892, 'eye': 893, 'okay': 894, 'looks': 895, 'shake': 896, 'anybody': 897, 'wants': 898, 'count': 899, 'embrace': 900, 'complicated': 901, 'hundred': 902, 'practice': 903, 'country': 904, 'endless': 905, 'emotions': 906, 'reward': 907, 'fill': 908, 'avoid': 909, 'secrets': 910, 'valuable': 911, 'although': 912, 'adversity': 913, 'fulfill': 914, 'trouble': 915, 'discovery': 916, 'justice': 917, 'dengan': 918, 'took': 919, 'de': 920, 'drive': 921, 'miracle': 922, 'mess': 923, 'gonna': 924, 'smiling': 925, 'someday': 926, 'helping': 927, 'mad': 928, 'chosen': 929, 'hour': 930, 'grief': 931, 'you’ll': 932, 'storm': 933, 'neither': 934, 'misery': 935, 'hero': 936, 'painful': 937, 'defeat': 938, 'miserable': 939, 'you’ve': 940, 'finally': 941, 'clouds': 942, 'revolution': 943, 'candle': 944, 'blessed': 945, 'flow': 946, 'vision': 947, 'expectations': 948, 'attention': 949, 'easier': 950, 'beliefs': 951, 'stopped': 952, 'slowly': 953, 'language': 954, 'blind': 955, 'youth': 956, 'tear': 957, 'breath': 958, 'mine': 959, 'entire': 960, 'results': 961, 'poison': 962, 'fast': 963, 'faces': 964, 'curiosity': 965, 'havent': 966, 'fine': 967, 'allows': 968, 'edge': 969, 'envy': 970, 'humility': 971, 'butterfly': 972, 'result': 973, 'shadow': 974, 'pull': 975, 'determines': 976, 'five': 977, 'garden': 978, 'precious': 979, 'job': 980, 'dancing': 981, 'scars': 982, 'loneliness': 983, 'discipline': 984, 'peoples': 985, 'talking': 986, 'ought': 987, 'blessings': 988, 'search': 989, 'lust': 990, 'imperfect': 991, 'protect': 992, 'nation': 993, 'gold': 994, 'powers': 995, 'becoming': 996, 'till': 997, 'buy': 998, 'position': 999, 'family': 1000, 'leaders': 1001, 'image': 1002, 'boys': 1003, 'lay': 1004, 'process': 1005, 'started': 1006, 'arms': 1007, 'society': 1008, 'humans': 1009, 'sound': 1010, 'rule': 1011, 'growth': 1012, 'leads': 1013, 'seeing': 1014, 'mo': 1015, 'pray': 1016, 'sees': 1017, 'capacity': 1018, 'fish': 1019, 'mystery': 1020, 'opposite': 1021, 'shoes': 1022, 'pretty': 1023, 'final': 1024, 'continue': 1025, 'wounds': 1026, 'healing': 1027, 'seem': 1028, 'tiny': 1029, 'survival': 1030, 'corner': 1031, 'won’t': 1032, 'walked': 1033, 'wrote': 1034, 'inevitable': 1035, 'fire': 1036, 'spark': 1037, 'exists': 1038, 'empty': 1039, 'belongs': 1040, 'longing': 1041, 'weakness': 1042, 'spring': 1043, 'naked': 1044, 'fully': 1045, 'hidden': 1046, 'hair': 1047, 'cry': 1048, 'number': 1049, 'goodness': 1050, 'pride': 1051, 'useless': 1052, 'caring': 1053, 'spread': 1054, 'taste': 1055, 'storms': 1056, 'tale': 1057, 'holy': 1058, 'couldnt': 1059, 'shape': 1060, 'shoot': 1061, 'brings': 1062, 'window': 1063, 'integrity': 1064, 'anywhere': 1065, 'thank': 1066, 'someones': 1067, 'risks': 1068, 'paper': 1069, 'sleep': 1070, 'creatures': 1071, 'flaws': 1072, 'appear': 1073, 'falling': 1074, 'if…you': 1075, 'day…you': 1076, 'grasp': 1077, 'teaches': 1078, 'crazy': 1079, 'rainbow': 1080, 'biggest': 1081, 'herself': 1082, 'saw': 1083, 'tough': 1084, 'reflection': 1085, 'parts': 1086, 'listening': 1087, 'kill': 1088, 'kiss': 1089, 'game': 1090, 'reached': 1091, 'security': 1092, 'fallen': 1093, 'father': 1094, 'content': 1095, 'happening': 1096, 'line': 1097, 'necessarily': 1098, 'version': 1099, 'further': 1100, 'tak': 1101, 'kita': 1102, 'catch': 1103, 'possibilities': 1104, 'improve': 1105, 'shut': 1106, 'chase': 1107, 'keeping': 1108, 'settle': 1109, 'prove': 1110, 'illusion': 1111, 'ours': 1112, 'mere': 1113, 'turns': 1114, 'strange': 1115, 'ng': 1116, 'overcome': 1117, 'answers': 1118, 'consider': 1119, 'brief': 1120, 'differences': 1121, 'flower': 1122, 'writer': 1123, 'mankind': 1124, 'nations': 1125, 'extraordinary': 1126, 'pick': 1127, 'america': 1128, 'invisible': 1129, 'dia': 1130, 'boredom': 1131, 'eternity': 1132, 'watching': 1133, 'madness': 1134, 'fairy': 1135, 'dreamer': 1136, 'talented': 1137, 'supposed': 1138, 'attack': 1139, 'everyday': 1140, 'front': 1141, 'went': 1142, 'places': 1143, 'fair': 1144, 'refuse': 1145, 'crawl': 1146, 'deeds': 1147, 'strive': 1148, 'grab': 1149, 'careful': 1150, 'add': 1151, 'energy': 1152, 'fun': 1153, 'prince': 1154, 'level': 1155, 'aware': 1156, 'hours': 1157, 'flight': 1158, 'succeed': 1159, 'perfectly': 1160, 'weep': 1161, 'according': 1162, 'acceptance': 1163, 'completely': 1164, 'ending': 1165, 'following': 1166, 'held': 1167, 'track': 1168, 'quiet': 1169, 'horizon': 1170, 'honor': 1171, 'tells': 1172, 'dreamed': 1173, 'hide': 1174, 'working': 1175, 'brick': 1176, 'age': 1177, 'greatness': 1178, 'slow': 1179, 'what’s': 1180, 'rights': 1181, 'sunshine': 1182, 'struggle': 1183, 'nonsense': 1184, 'moon': 1185, 'constantly': 1186, 'deal': 1187, 'showing': 1188, 'arrogance': 1189, 'roads': 1190, 'teacher': 1191, 'scared': 1192, 'surround': 1193, 'looked': 1194, 'ruin': 1195, 'yo': 1196, 'generosity': 1197, 'follows': 1198, 'comfortable': 1199, 'lesson': 1200, 'develop': 1201, 'gave': 1202, 'bend': 1203, 'doors': 1204, 'gentle': 1205, 'huge': 1206, 'seemed': 1207, 'standing': 1208, 'woods': 1209, 'dreaming': 1210, 'values': 1211, 'inspiration': 1212, 'cake': 1213, 'hopes': 1214, 'plans': 1215, 'object': 1216, 'despite': 1217, 'stage': 1218, 'bliss': 1219, 'allowing': 1220, 'happier': 1221, 'theory': 1222, 'whenever': 1223, 'calm': 1224, 'breathe': 1225, 'moral': 1226, 'shoulder': 1227, 'fake': 1228, 'pleasure': 1229, 'satisfied': 1230, 'jika': 1231, 'holding': 1232, 'finished': 1233, 'christian': 1234, 'useful': 1235, 'kinds': 1236, 'deny': 1237, 'obstacles': 1238, 'connect': 1239, 'ignorance': 1240, 'bitter': 1241, 'race': 1242, 'cut': 1243, 'material': 1244, 'welcome': 1245, 'sign': 1246, 'events': 1247, 'soft': 1248, 'ashamed': 1249, 'root': 1250, 'eternal': 1251, 'cross': 1252, 'ten': 1253, 'understood': 1254, 'considered': 1255, 'ease': 1256, 'highest': 1257, 'noble': 1258, 'education': 1259, 'searching': 1260, 'starts': 1261, 'probably': 1262, 'promises': 1263, 'praise': 1264, 'leader': 1265, 'ugly': 1266, 'determined': 1267, 'unhappiness': 1268, 'ocean': 1269, 'wide': 1270, 'lebih': 1271, 'reasons': 1272, 'selfish': 1273, 'gain': 1274, 'millions': 1275, 'grey': 1276, 'sake': 1277, 'liked': 1278, 'summer': 1279, 'saya': 1280, 'dragons': 1281, 'failed': 1282, 'indifference': 1283, 'artist': 1284, 'draw': 1285, 'brains': 1286, 'girls': 1287, 'creating': 1288, 'closed': 1289, 'opened': 1290, 'counts': 1291, 'glory': 1292, 'possibility': 1293, 'interesting': 1294, 'onto': 1295, 'isn’t': 1296, 'guy': 1297, 'warm': 1298, 'hurts': 1299, 'beat': 1300, 'boats': 1301, 'please': 1302, 'philosophy': 1303, 'wrongs': 1304, 'excuse': 1305, 'facts': 1306, 'laughter': 1307, 'survive': 1308, 'grew': 1309, 'hopeless': 1310, 'lonely': 1311, 'fantasy': 1312, 'points': 1313, 'kick': 1314, 'asking': 1315, 'seeds': 1316, 'plant': 1317, 'somehow': 1318, 'instant': 1319, 'flame': 1320, 'encounter': 1321, 'b': 1322, 'role': 1323, 'dwell': 1324, 'judgment': 1325, 'danger': 1326, 'pretend': 1327, 'grain': 1328, 'sort': 1329, 'jealous': 1330, 'mirror': 1331, 'fearless': 1332, 'affect': 1333, 'harry': 1334, 'stone': 1335, 'acts': 1336, 'regrets': 1337, 'accepting': 1338, 'forces': 1339, 'piece': 1340, 'cool': 1341, 'focused': 1342, 'sleeping': 1343, 'reputation': 1344, 'respond': 1345, 'top': 1346, 'damage': 1347, 'helped': 1348, 'pages': 1349, 'facing': 1350, 'concern': 1351, 'they’re': 1352, 'red': 1353, 'emotio

In [73]:
from tensorflow.keras.utils import to_categorical
y1=np.array(y1)
vocab_size = max(y1.max(), max(tokenizer.word_index.values())) + 1

print("Vocabulary size:", vocab_size)
print("Maximum y1 value:", y1.max())
y_one_hot = to_categorical(
    y1,
    num_classes=vocab_size
)

print("y_one_hot shape:", y_one_hot.shape)

Vocabulary size: 7752
Maximum y1 value: 7751
y_one_hot shape: (79812, 7752)

In [74]:
y_one_hot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(79812, 7752))

In [78]:
X = pad_sequences(
    X,
   
    padding="post",
)

In [79]:
X

array([[ 13,   0,   0, ...,   0,   0,   0],
       [ 13,  60,   0, ...,   0,   0,   0],
       [ 13,  60, 217, ...,   0,   0,   0],
       ...,
       [ 20,   9,   1, ...,   0,   0,   0],
       [ 20,   9,   1, ...,   0,   0,   0],
       [ 20,   9,   1, ...,   0,   0,   0]],
      shape=(79812, 287), dtype=int32)

In [81]:
vocab_size = int(max(y1.max(), max(tokenizer.word_index.values())) + 1)

print(vocab_size)
print(type(vocab_size))

7752
<class 'int'>

In [82]:
model = Sequential([
    Input(shape=(X.shape[1],)),

    Embedding(
        input_dim=vocab_size,
        output_dim=128,
        mask_zero=True
    ),

    SimpleRNN(128),

    Dense(vocab_size, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)